replicaCount: 3

auth:
  rootPassword: rootpassword
  database: taskmanager
  username: appuser
  password: appuserpass

persistence:
  enabled: true
  size: 5Gi

galera:
  bootstrap:
    forceSafeToBootstrap: true
    bootstrapFromNode: "my-galera-mariadb-galera-0"  # Utilise un nœud comme point de démarrage

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m

service:
  type: ClusterIP
  name: my-galera-mariadb-galera  # Nom personnalisé du service
  ports:
    mysql: 3306
